# Generated by Django 5.0.4 on 2024-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_remove_product_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AlterField(
            model_name='filter_price',
            name='price',
            field=models.CharField(choices=[('10000 TO 20000', '1000 TO 20000'), ('20000 TO 30000', '20000 TO 30000'), ('30000 TO 40000', '30000 TO 40000'), ('50000 TO 60000', '50000 TO 60000'), ('60000 TO 70000', '60000 TO 70000')], max_length=50),
        ),
    ]
